events {}

# Define un grupo de servidores
http {
    upstream libro_backend {        
        # Por defecto, NGINX usa Round Robin aquí (reparte en orden)         

        #Los nombres de los servidores backend se pueden definir como IPs o nombres de host

        #least_conn;
        server libro1:8080;
        server libro2:8080;
        server libro3:8080;

    }
  # Configura el servidor que escucha las peticiones HTTP
    server {
        listen 80;

        location / { 
            proxy_pass http://libro_backend; # Se reenvían al grupo de servidores backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
